Update Markdown support for Approvals Teams app
MicrosoftDocs/power-automate-docs pull request #405
Opened 2021-02-16 20:52 UTC by mukhole

Approvals Teams app currently does not support Markdown.
The documentation is not clearly stating this, causing confusion among users.
This change is to clearly state that the Approvals App on Teams does not currently support Markdown.

2021-02-16 20:53 UTC, PRMerger19 commented
@mukhole : Thanks for your contribution! The author(s) have been notified to review your proposed change. @gcorvera

2021-02-16 22:19 UTC, PRMerger10 commented
@mukhole : Thanks for your contribution! The author(s) have been notified to review your proposed change. @gcorvera

2021-02-17 04:58 UTC, dblyth-msft requested changes

2021-02-17 04:58 UTC, dblyth-msft commented on articles/approvals-markdown-support.md
> +> - Markdown is not currently supported for Approvals app on Teams, but is expected soon.
I'd say "in March 2021"

2021-02-18 16:12 UTC, PRMerger8 commented
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @gcorvera

2021-02-18 16:15 UTC, PRMerger9 commented
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @gcorvera

2021-02-18 16:23 UTC, MSFTMan reviewed
@dblyth-msft I am not seeing the term FlowBot as an approved term, so I'll remove it from the PR. Kindly let me know if this gets approved and added to the style guide.

2021-02-18 16:24 UTC, PRMerger12 commented
@MSFTMan : Thanks for your contribution! The author(s) have been notified to review your proposed change. @gcorvera

2021-02-18 16:24 UTC, MSFTMan approved these changes

2021-02-18 16:25 UTC, merged